### ISSUE TITLE
When 1.21 Support(1.21 지원 언제 하나요)

### ISSUE THREAD

**Issue by Outfit8TSB** [PlazmaMC/PlazmaBukkit#101]
KR:
1.21은 ViaVersion 설치하면 되긴 합니다만
1.21의 아이템을 맛볼수가 없어요. 
(플라즈마 업데이트 대기하겠습니다.)
EN:
I Could Install ViaVersion In Plugins folder
But How can i Use the 1.21 item when ViaVersion for 1.21(1.20.6+) Never support them?
(I Will Wait for update.)

**Comment by IPECTER** [comment]
Purpur and Paper is on experiment builds.
We gonna update after they changed to stable.

**Comment by Outfit8TSB** [comment]
감사합니다.
(Thank you)

**Comment by Outfit8TSB** [comment]
퍼퍼랑 페이퍼 1.21 이제 안정버전 됐는데...
업데이트 소식이 아직도 없네요...
(Purpur and paper is now stable, but there is still no updates)

**Comment by IPECTER** [comment]
여긴 현생 있는 개발자 3명이 전부라 오래걸립니다 ^^
2달 뒤에 오세요

**Comment by Outfit8TSB** [comment]
알겠습니다

**Comment by Outfit8TSB** [comment]
2달 정도 다 지난 것 같은데 그 긴 시간이 지난 동안 Pufferfish가 드디어 1.21이 되고 Purpur가 Pufferfish를 다시 추가했다고 합니다.
Pufferfish 1.21 커밋: https://github.com/pufferfish-gg/Pufferfish/commit/0674c2b7c79cb3d6c80c52c79cce980becf0e0f1

Purpur의 Pufferfish 재추가 커밋: https://github.com/PurpurMC/Purpur/commit/201e928fa6966e16e4d8db16d7cf130c444836d0

이제 1.21 업데이트 때 https://github.com/PlazmaMC/Pufferfish https://github.com/PlazmaMC/Purpur 쓸 이유가 없어진 것 같습니다.

(Pufferfish finally updated to 1.21 and Purpur Has Added Back Pufferfish, so there is no more point for using PlazmaMC's Pufferfish/Purpur Fork repository.)
현재 Pufferfish 커밋: https://github.com/pufferfish-gg/Pufferfish/commit/a9e9d9940376e432d72cdebbdffcf40eb48bd713
현재 Purpur 커밋: https://github.com/PurpurMC/Purpur/commit/be61a07bf60547c02657b39cb90ceb4c0dc68883

**Comment by IPECTER** [comment]
1.21.2가 출시하면 1.21.1과 1.21.2를 출시하겠습니다
현재 새로운 개발자 영입을 시도중입니다

**Comment by AlphaKR93** [comment]
https://github.com/PlazmaMC/PlazmaBukkit/tree/dev/1.21.1

1.21(.1) 작업을 시작했습니다. 작업 중 Paper 1.21.2가 릴리스 되면 1.21.1 개발이 중단될 수 있습니다 (1.21.2로 바로 업그레이드 할 예정)
