### ISSUE TITLE
Bag in server minecraft

### ISSUE THREAD

**Issue by xDeizs** [PlazmaMC/PlazmaBukkit#57]
I installed and put the bukkit Plazma, on the server as if there is a protection from the world, it is about 9x10 or 10x9, within it you can break blocks, but behind it you can not, also you become a phantom when you are attacked by monsters, the damage comes from another place from monsters, all shown in the video below!

https://youtu.be/7yJslgX63oA
and 2 bug
https://youtu.be/wkmoeVvNjMo

**Comment by AlphaKR93** [comment]
Version?

**Comment by AlphaKR93** [comment]
Fixed in 922c33171ca438553d597acbc28715ad4e21b670, 1.20.2
