### ISSUE TITLE
add SparklyPower optimizations 

### ISSUE THREAD

**Issue by Cestis** [PlazmaMC/PlazmaBukkit#73]
[https://github.com/SparklyPower/SparklyPaper](https://github.com/SparklyPower/SparklyPaper)

**Comment by IPECTER** [comment]
WIP..!

**Comment by AlphaKR93** [comment]
will be added to 1.20.4

**Comment by AlphaKR93** [comment]
Completely added to 1.20.6!
It will also be backported later on 1.20.4 :)
