### ISSUE TITLE
Please help me AuthLib (1.20.1)

### ISSUE THREAD

**Issue by imtorich** [PlazmaMC/PlazmaBukkit#76]
Sometimes on some players spam console warning, but, at the same time previously everything worked correctly, this happened after updating to 8+ versions of plazma - to the current version. Check it out, maybe you've done something wrong) 
In the server plugins is ruled out, it can only be in the kernel..... 
You can see the warnings on line 1028.
https://pastes.dev/PrGF7PFVCz

**Comment by imtorich** [comment]
> ver
[18:10:55 INFO]: Current: git-Plazma-"9871a13" (MC: 1.20.1)*
Previous: git-Plazma-"8348420" (MC: 1.20.1)
* You are running the latest version

**Comment by imtorich** [comment]
On version git-Plazma-"8348420" (MC: 1.20.1)
That didn't happen fortunately, no other changes on the server.

**Comment by AlphaKR93** [comment]
Can you upload the global configuration and world configuration of Plazma?

**Comment by imtorich** [comment]
> Can you upload the global configuration and world configuration of Plazma?

https://mega.nz/file/zm4g2ADT#GFlhLxQbzoWECMYE0ZtXPuiR11DDNv_M3vGFLIo3Ovo Full config

**Comment by AlphaKR93** [comment]
This is a problem with the Mojang authentication server. Even if it is an offline server, it can occur once the authentication server goes down because the server sends a Heartbeat signal to the Mojang server.
